language: node_js
node_js: node
os: osx
script: echo $PATH
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/11a3bbb28024d4c9097f
    on_success: always
    on_failure: always
    on_start: always
  email:
    recipients:
    - noah@noahandrews.me
    on_success: always
    on_failure: always
